### ISSUE TITLE
Impressions and comments

### ISSUE THREAD

**Issue by eliasmalik** [SupervisionT/Leaflet.PolylineMeasure#1]
Usually, when you want to make changes to someone elses repo, you should _fork_ it. That way there’s a clear link to the original, so that attribution is to some extent automatic. Even so, I would also usually add an attribution in the README that links to the original.

Just so you know, if you fork a repo, it is easy to make pull requests from your version into the original. This is how many people begin making open source contributions.

I had a quick look at what you changed but to be honest, I would need a really good understanding of the original library to understand your changes properly.

The bad thing about the original library is that there are no tests (as far as I can see).  That means that you can’t easily tell if your changes broke some of the original functionality. From a quick look at your changes, it looks like you have at least removed some functionality (like displaying distance in nautical miles, or removing the `measureControlTitleOn/Off` flags).

I would create an issue in the original repo explaining the changes you’ve made and asking for the owner’s advice for:
(1) whether he wants the functionality you’ve added in his library
(2) what the best way would be to include that functionality without breaking existing features.

👍

**Comment by SupervisionT** [comment]
Thank you Elias 👍
